version: '3.8'
services:
  movies:
    image: pratikshabansod1/instagram
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: pratikshabansod1/facebook
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: pratikshabansod1/whatsaap
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: pratikshabansod1/telegram
    ports:
      - "84:80"
    deploy:
      replicas: 3
